name: Unit Tests

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Unit Tests

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Unit Tests ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test
